export const SET_SEARCH = "SET_SEARCH";
export const SET_GENRES = "SET_GENRES";
export const SET_SEARCHLOAD = "SET_SEARCHLOAD";
export const SET_SEARCHPAGINATION = "SET_SEARCHPAGINATION";
export const SET_SEARCHTEXT = "SET_SEARCHTEXT";
